import { StyleSheet } from "react-native";
import { palette, radius } from "../theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  flex: {
    flex: 1,
  },
  appShell: {
    flex: 1,
    backgroundColor: palette.background,
  },
  loadingState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
  },
  loadingLogo: {
    width: 260,
    height: 220,
  },
  loadingDropWrap: {
    width: 58,
    height: 58,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingRipple: {
    position: "absolute",
    width: 46,
    height: 46,
    borderWidth: 2,
    borderColor: palette.accent,
    borderRadius: 999,
    backgroundColor: palette.tintStrong,
  },
  loadingDrop: {
    width: 28,
    height: 28,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 5,
    backgroundColor: palette.accent,
  },
  loadingDropHighlight: {
    position: "absolute",
    top: 19,
    left: 24,
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: palette.surface,
    opacity: 0.78,
  },
  loadingText: {
    color: palette.muted,
    fontSize: 15,
    fontWeight: "700",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 4,
  },
  brand: {
    color: palette.ink,
    fontSize: 28,
    fontWeight: "600",
    letterSpacing: 0,
  },
  headerLogo: {
    width: 132,
    height: 54,
    alignSelf: "flex-start",
  },
  headerSubcopy: {
    color: palette.muted,
    fontSize: 13,
    marginTop: 2,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  modePill: {
    minHeight: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: palette.surfaceTint,
    paddingHorizontal: 12,
  },
  modePillText: {
    color: palette.accent,
    fontSize: 12,
    fontWeight: "600",
  },
  iconButton: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: palette.surfaceTint,
  },
  bleHeaderButtonWrap: {
    position: "relative",
  },
  bleHeaderActivityGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  bleActivityIconSlot: {
    width: 18,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  bleActivityIcon: {
    width: 16,
    height: 16,
    tintColor: palette.accent,
  },
  bleConnectionDot: {
    position: "absolute",
    right: 4,
    top: 4,
    width: 9,
    height: 9,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: palette.surface,
  },
  bleConnectionDotConnected: {
    backgroundColor: palette.accent,
  },
  bleConnectionDotDisconnected: {
    backgroundColor: palette.danger,
  },
  notice: {
    position: "absolute",
    top: 76,
    left: 20,
    right: 20,
    zIndex: 20,
    elevation: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: radius.md,
    backgroundColor: palette.surfaceTint,
    padding: 12,
    shadowColor: palette.ink,
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  noticeWarn: {
    backgroundColor: "#FFF4E2",
  },
  noticeDanger: {
    backgroundColor: "#FDEDEB",
  },
  noticeText: {
    flex: 1,
    color: palette.accentDark,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  noticeTextWarn: {
    color: palette.warning,
  },
  noticeTextDanger: {
    color: palette.danger,
  },
  noticeCloseButton: {
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
  },
  noticeTimeoutBar: {
    position: "absolute",
    left: 0,
    bottom: 0,
    height: 3,
    borderBottomLeftRadius: radius.md,
    borderBottomRightRadius: radius.md,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 110,
  },
  pageTransition: {
    flex: 1,
  },
  screenCard: {
    minHeight: 620,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.xl,
    backgroundColor: palette.surface,
    padding: 18,
    shadowColor: palette.ink,
    shadowOpacity: 0.08,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 3,
  },
  screenHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 18,
  },
  screenTitleBlock: {
    flex: 1,
  },
  screenTitle: {
    color: palette.ink,
    fontSize: 21,
    lineHeight: 25,
    fontWeight: "600",
    letterSpacing: 0,
  },
  screenSubtitle: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  statusPill: {
    minHeight: 32,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 999,
    paddingHorizontal: 10,
  },
  pillNormal: {
    backgroundColor: palette.tintStrong,
  },
  pillWarn: {
    backgroundColor: "#FFF1DE",
  },
  pillDanger: {
    backgroundColor: "#FDEDEB",
  },
  statusPillText: {
    color: palette.accent,
    fontSize: 12,
    fontWeight: "600",
  },
  statusPillTextWarn: {
    color: palette.warning,
  },
  statusPillTextDanger: {
    color: palette.danger,
  },
  bottlePanel: {
    borderRadius: radius.lg,
    backgroundColor: palette.surfaceTint,
    padding: 18,
    gap: 18,
  },
  bottleBadge: {
    alignSelf: "center",
    width: 132,
    height: 132,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 34,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  bottleBadgeText: {
    color: palette.accent,
    fontSize: 13,
    fontWeight: "900",
    marginTop: 6,
  },
  bottleBadgeLogo: {
    width: 112,
    height: 112,
  },
  softPanel: {
    borderRadius: radius.lg,
    backgroundColor: palette.surfaceTint,
    padding: 18,
    gap: 12,
  },
  calibrationPanelStack: {
    gap: 14,
  },
  panelTitle: {
    color: palette.ink,
    fontSize: 20,
    fontWeight: "600",
  },
  panelBody: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  stepDots: {
    flexDirection: "row",
    gap: 8,
    marginTop: 6,
  },
  stepDot: {
    flex: 1,
    height: 6,
    borderRadius: 999,
    backgroundColor: palette.tintStrong,
  },
  stepDotActive: {
    backgroundColor: palette.accent,
  },
  progressWrap: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 210,
  },
  progressSvg: {
    transform: [{ rotate: "0deg" }],
  },
  progressText: {
    position: "absolute",
    alignItems: "center",
  },
  progressValue: {
    color: palette.ink,
    fontSize: 46,
    lineHeight: 52,
    fontWeight: "900",
  },
  progressLabel: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "700",
  },
  metricGrid: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  manualSaveAction: {
    marginTop: 18,
  },
  metricCard: {
    flex: 1,
    minHeight: 72,
    justifyContent: "center",
    borderRadius: radius.md,
    backgroundColor: palette.surfaceTint,
    padding: 13,
  },
  metricLabel: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  metricValue: {
    color: palette.ink,
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "600",
    marginTop: 4,
  },
  infoList: {
    overflow: "hidden",
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.md,
    backgroundColor: palette.surface,
    marginTop: 14,
  },
  infoRow: {
    minHeight: 66,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  infoCopy: {
    flex: 1,
  },
  infoLabel: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  infoValue: {
    color: palette.ink,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "600",
    marginTop: 3,
  },
  infoMeta: {
    color: palette.ink,
    fontSize: 12,
    fontWeight: "600",
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
  },
  bottleScanPanel: {
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.md,
    backgroundColor: palette.surface,
    padding: 13,
    gap: 10,
    marginTop: 14,
  },
  bottleScanItem: {
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.sm,
    backgroundColor: palette.surfaceTint,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  bottleScanMeta: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
    marginTop: 4,
  },
  bleLogToggle: {
    alignSelf: "flex-start",
    minHeight: 36,
    justifyContent: "center",
    marginTop: 12,
    paddingVertical: 4,
  },
  bleLogToggleText: {
    color: palette.accent,
    fontSize: 14,
    fontWeight: "700",
  },
  bleLogPanel: {
    borderTopWidth: 1,
    borderTopColor: palette.line,
    backgroundColor: palette.surfaceTint,
    marginTop: 2,
    paddingTop: 12,
  },
  bleLogHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  bleLogClearButton: {
    justifyContent: "center",
    minHeight: 32,
    paddingVertical: 4,
  },
  bleLogClearButtonText: {
    color: palette.danger,
    fontSize: 13,
    fontWeight: "700",
  },
  bleLogFilterGroup: {
    marginTop: 12,
  },
  bleLogFilterLabel: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
    marginBottom: 6,
  },
  bleLogFilterChoices: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  bleLogFilterChoice: {
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.sm,
    minHeight: 32,
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  bleLogFilterChoiceActive: {
    borderColor: palette.accent,
    backgroundColor: palette.tintStrong,
  },
  bleLogFilterChoiceText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "600",
  },
  bleLogFilterChoiceTextActive: {
    color: palette.accentDark,
  },
  bleLogEmpty: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "600",
    marginTop: 8,
  },
  bleLogEntry: {
    flexDirection: "row",
    alignItems: "flex-start",
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    gap: 8,
    paddingVertical: 9,
  },
  bleLogDirectionIcon: {
    width: 14,
    height: 14,
    marginTop: 2,
    tintColor: palette.accent,
  },
  bleLogEntryBody: {
    flex: 1,
    minWidth: 0,
  },
  bleLogEntryMeta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  bleLogDirection: {
    color: palette.ink,
    fontSize: 11,
    fontWeight: "800",
  },
  bleLogCharacteristic: {
    color: palette.accent,
    fontSize: 11,
    fontWeight: "700",
  },
  bleLogTime: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "600",
  },
  bleLogField: {
    marginTop: 7,
  },
  bleLogFieldLabel: {
    color: palette.muted,
    fontSize: 10,
    fontWeight: "700",
    marginBottom: 2,
    textTransform: "uppercase",
  },
  bleLogPayload: {
    color: palette.ink,
    fontFamily: "monospace",
    fontSize: 11,
    lineHeight: 16,
  },
  primaryButton: {
    flex: 1,
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: radius.md,
    backgroundColor: palette.accent,
    paddingHorizontal: 14,
  },
  primaryButtonDanger: {
    backgroundColor: palette.danger,
  },
  primaryButtonText: {
    color: palette.surface,
    fontSize: 15,
    fontWeight: "600",
    flexShrink: 1,
    textAlign: "center",
  },
  secondaryButton: {
    flex: 1,
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: radius.md,
    backgroundColor: palette.tintStrong,
    paddingHorizontal: 8,
  },
  secondaryButtonText: {
    color: palette.accent,
    fontSize: 14,
    fontWeight: "600",
    flexShrink: 1,
    textAlign: "center",
  },
  buttonPressed: {
    backgroundColor: palette.accentDark,
  },
  buttonPressedDanger: {
    backgroundColor: "#A94B40",
  },
  secondaryButtonPressed: {
    opacity: 0.72,
  },
  secondaryButtonDisabled: {
    backgroundColor: palette.surfaceTint,
  },
  secondaryButtonTextDisabled: {
    color: palette.disabled,
  },
  buttonDisabled: {
    backgroundColor: palette.disabled,
  },
  amountPanel: {
    borderRadius: radius.lg,
    backgroundColor: palette.surfaceTint,
    padding: 18,
  },
  inputLabel: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "700",
  },
  amountInputRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "center",
    marginVertical: 14,
  },
  amountInput: {
    minWidth: 112,
    color: palette.ink,
    fontSize: 50,
    lineHeight: 58,
    fontWeight: "900",
    textAlign: "right",
    padding: 0,
  },
  amountUnit: {
    color: palette.muted,
    fontSize: 18,
    fontWeight: "600",
    marginLeft: 8,
  },
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
  },
  categoryButton: {
    width: "48%",
    minHeight: 52,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.md,
    backgroundColor: palette.surface,
    paddingHorizontal: 12,
  },
  categoryButtonActive: {
    borderColor: palette.accent,
    backgroundColor: palette.tintStrong,
  },
  categoryText: {
    color: palette.ink,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
  },
  categoryTextActive: {
    color: palette.accentDark,
  },
  noteInput: {
    minHeight: 54,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.md,
    color: palette.ink,
    backgroundColor: palette.surface,
    paddingHorizontal: 14,
    marginTop: 14,
    fontSize: 15,
    fontWeight: "700",
  },
  datePanel: {
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.md,
    backgroundColor: palette.surface,
    padding: 13,
    marginTop: 14,
  },
  dateInput: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.sm,
    color: palette.ink,
    backgroundColor: palette.surfaceTint,
    paddingHorizontal: 12,
    marginTop: 8,
    fontSize: 15,
    fontWeight: "700",
  },
  pickerControlRow: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 8,
    marginBottom: 10,
  },
  datePickerButton: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.sm,
    backgroundColor: palette.surfaceTint,
    paddingHorizontal: 12,
    marginTop: 8,
    marginBottom: 10,
  },
  datePickerButtonPressed: {
    backgroundColor: palette.tintStrong,
  },
  datePickerButtonText: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: "800",
  },
  datePickerInline: {
    marginBottom: 10,
  },
  clockInput: {
    flex: 1,
    minHeight: 44,
    textAlign: "center",
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.sm,
    color: palette.ink,
    backgroundColor: palette.surfaceTint,
    paddingHorizontal: 12,
    fontSize: 15,
    fontWeight: "800",
  },
  dateInputInvalid: {
    borderColor: palette.danger,
    backgroundColor: "#FDEDEB",
  },
  dateHint: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
    marginTop: 6,
  },
  dateHintInvalid: {
    color: palette.danger,
  },
  segmentControl: {
    flexDirection: "row",
    gap: 8,
    borderRadius: radius.md,
    backgroundColor: palette.surfaceTint,
    padding: 6,
    marginBottom: 12,
  },
  segmentButton: {
    flex: 1,
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  segmentButtonActive: {
    backgroundColor: palette.surface,
  },
  segmentButtonText: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "600",
  },
  segmentButtonTextActive: {
    color: palette.accent,
  },
  historyToolbar: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  periodSelector: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 10,
  },
  periodTitleBlock: {
    flex: 1,
    minHeight: 56,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.md,
    backgroundColor: palette.surface,
    paddingHorizontal: 14,
  },
  monthPickerPanel: {
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.md,
    backgroundColor: palette.surface,
    padding: 12,
    marginBottom: 12,
  },
  monthPickerHeader: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  monthPickerYear: {
    flex: 1,
    color: palette.ink,
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  monthPickerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  monthPickerOption: {
    width: "31%",
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.sm,
    backgroundColor: palette.surfaceTint,
  },
  monthPickerOptionActive: {
    borderColor: palette.accent,
    backgroundColor: palette.tintStrong,
  },
  monthPickerOptionText: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: "800",
  },
  monthPickerOptionTextActive: {
    color: palette.accentDark,
  },
  periodType: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  periodTitle: {
    color: palette.ink,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "600",
    marginTop: 2,
  },
  chartPanel: {
    minHeight: 188,
    gap: 10,
    overflow: "visible",
    borderRadius: radius.lg,
    backgroundColor: palette.surfaceTint,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
  },
  chartTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    minHeight: 24,
  },
  chartUnitLabel: {
    color: palette.ink,
    fontSize: 12,
    fontWeight: "900",
  },
  chartLegend: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 8,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: palette.accent,
  },
  legendDotManual: {
    backgroundColor: palette.coral,
  },
  legendText: {
    color: palette.muted,
    fontSize: 10,
    fontWeight: "600",
  },
  chartBody: {
    minHeight: 144,
    flexDirection: "row",
    gap: 8,
  },
  volumeAxis: {
    width: 20,
    paddingTop: 8,
    paddingBottom: 24,
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  volumeTick: {
    color: palette.muted,
    fontSize: 10,
    fontWeight: "600",
  },
  chartPlot: {
    flex: 1,
    position: "relative",
    overflow: "visible",
  },
  chartGrid: {
    position: "absolute",
    top: 8,
    right: 0,
    bottom: 24,
    left: 0,
    justifyContent: "space-between",
  },
  chartGridLine: {
    height: 1,
    backgroundColor: palette.line,
    opacity: 0.7,
  },
  chartBars: {
    flex: 1,
    flexDirection: "row",
    alignItems: "stretch",
    gap: 7,
  },
  barColumn: {
    flex: 1,
    minWidth: 20,
    alignItems: "center",
    justifyContent: "flex-end",
    overflow: "visible",
  },
  barTrack: {
    width: "100%",
    flex: 1,
    minHeight: 98,
    alignItems: "center",
    justifyContent: "flex-end",
    paddingTop: 8,
    overflow: "visible",
  },
  barStack: {
    width: "58%",
    minWidth: 9,
    maxWidth: 24,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: palette.line,
  },
  barSegment: {
    width: "100%",
    minHeight: 2,
  },
  barSegmentAuto: {
    backgroundColor: palette.accent,
  },
  barSegmentManual: {
    backgroundColor: palette.coral,
  },
  barSegmentOther: {
    backgroundColor: palette.warning,
  },
  barSelected: {
    borderWidth: 2,
    borderColor: palette.ink,
  },
  barTooltip: {
    position: "absolute",
    top: 0,
    zIndex: 2,
    minWidth: 76,
    alignItems: "center",
    borderRadius: 999,
    backgroundColor: palette.ink,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  barTooltipText: {
    color: palette.surface,
    fontSize: 10,
    fontWeight: "900",
    flexShrink: 0,
  },
  barLabel: {
    height: 20,
    marginTop: 6,
    color: palette.muted,
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
  },
  timeline: {
    gap: 14,
    marginTop: 18,
  },
  historyDateGroup: {
    gap: 10,
  },
  historyDateHeader: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  timelineRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  timelineDot: {
    width: 11,
    height: 11,
    borderRadius: 999,
    backgroundColor: palette.accent,
  },
  timelineDotWarn: {
    backgroundColor: palette.warning,
  },
  timelineDotDanger: {
    backgroundColor: palette.danger,
  },
  timelineCopy: {
    flex: 1,
  },
  timelineTitle: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "600",
  },
  timelineDetail: {
    color: palette.muted,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 2,
  },
  timelineMeta: {
    color: palette.ink,
    fontSize: 12,
    fontWeight: "600",
  },
  emptyHistoryState: {
    minHeight: 96,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.md,
    backgroundColor: palette.surfaceTint,
  },
  emptyHistoryText: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "700",
  },
  historyActionPanel: {
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.lg,
    backgroundColor: palette.surfaceTint,
    padding: 14,
    marginTop: 18,
  },
  settingsSectionLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 8,
    textTransform: "uppercase",
  },
  deviceSettingsPanel: {
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.md,
    backgroundColor: palette.surface,
    marginBottom: 14,
    overflow: "hidden",
  },
  deviceSettingsHeader: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 13,
  },
  deviceSettingsHeaderPressed: {
    backgroundColor: palette.surfaceTint,
  },
  deviceSettingsTitle: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "800",
  },
  deviceSettingsContent: {
    borderTopWidth: 1,
    borderTopColor: palette.line,
    padding: 10,
    paddingBottom: 0,
  },
  settingRow: {
    minHeight: 74,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.md,
    backgroundColor: palette.surface,
    paddingHorizontal: 13,
    marginBottom: 10,
  },
  settingText: {
    flex: 1,
  },
  languageChoices: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    backgroundColor: palette.surfaceTint,
    padding: 4,
  },
  languageChoice: {
    minHeight: 34,
    minWidth: 74,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    paddingHorizontal: 10,
  },
  languageChoiceActive: {
    backgroundColor: palette.surface,
  },
  languageChoiceText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "600",
  },
  languageChoiceTextActive: {
    color: palette.accent,
  },
  historySyncChoices: {
    flexDirection: "row",
    alignItems: "stretch",
    width: 164,
    gap: 4,
    borderRadius: radius.md,
    backgroundColor: palette.surfaceTint,
    padding: 4,
  },
  historySyncChoice: {
    flex: 1,
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.sm,
    paddingHorizontal: 4,
  },
  historySyncChoiceActive: {
    backgroundColor: palette.surface,
  },
  historySyncChoiceText: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
  },
  historySyncChoiceTextActive: {
    color: palette.accent,
  },
  deviceManager: {
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.md,
    backgroundColor: palette.surface,
    padding: 13,
    marginBottom: 10,
  },
  deviceManagerHeader: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
  },
  deviceManagerId: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "600",
    marginTop: 3,
  },
  deviceManagerEditor: {
    marginTop: 12,
    gap: 10,
  },
  deviceManagerEditActions: {
    flexDirection: "row",
    gap: 10,
  },
  deviceManagerActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
  },
  stepperControls: {
    flexDirection: "row",
    gap: 8,
  },
  settingsActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
    marginBottom: 14,
  },
  bottomNav: {
    position: "absolute",
    left: 20,
    right: 20,
    bottom: 18,
    minHeight: 70,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: radius.lg,
    backgroundColor: palette.surface,
    overflow: "hidden",
    padding: 8,
    shadowColor: palette.ink,
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  navItem: {
    flex: 1,
    minHeight: 52,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.md,
    gap: 3,
  },
  navActiveIndicator: {
    position: "absolute",
    left: 8,
    top: 8,
    bottom: 8,
    borderRadius: radius.md,
    backgroundColor: palette.surfaceTint,
  },
  navLabel: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "600",
  },
  navLabelActive: {
    color: palette.accent,
  },
});
