// -------------------- Forward declarations --------------------

void showStatus(const String &line1, const String &line2, const String &line3);
void showBootLoading();
void startBootLoading();
void stopBootLoading();
bool shouldShowDeviceWarningIndicator();
void showMainDisplay();
void showBottleRemovedDisplay();
void drawBleStatusIndicator();
void showDrinkSavedDisplay(uint16_t amountMl);
void showRefillSavedDisplay(uint16_t amountMl);
void showFinalizationStatus(const String &line1, const String &line2);
void showTodayIntakeDisplay();
void showIntakeRecordDisplay(uint16_t ordinal, uint16_t amountMl, uint32_t timestamp, const String &type);
void showIntakeUnavailableDisplay(const String &reason);
void showTimeSyncDisplay(const DateTime &dt);
void showCalibrationStatus(const String &hint);
void serviceCountdownBar();
void clearSecondaryDisplayReturn();
void armSecondaryDisplayReturn(uint32_t timeoutMs);
bool secondaryDisplayReturnActive();
void serviceSecondaryDisplayTimeout();
void armSleepAfterStableRead();
void disarmSleepAfterStableRead();
bool stableReadFinalizationReady();
bool stableReadSleepReady();
void enterDeepSleep();
String buildStatusJson();
void updateStatusCharacteristic(bool notify);
void noteBleDataSent();
void noteBleDataReceived();
void serviceBleTransferIndicator();
void startBleAwakeAdvertising();
void exitBleSyncMode();
void noteEvent(const String &type, uint16_t amountMl);
void refreshTodayTotalFromHistory();
bool clearHistoryData();
void compactSyncedHistory();
bool finalizeStableWeightBeforeSleep();
bool appendRecord(const String &type, uint16_t amountMl, float beforeG, float afterG, const String &confidence, const String &flags);
void setDeviceWarning(const String &code, const String &message, uint8_t priority);
void clearDeviceWarning(const String &code);
void handleCommand(const String &command);
void startCalibrationMode();
void exitCalibrationMode();
void resetSavedDataExceptCalibrationAndSettings();
void advanceIntakeHistoryView();
void serviceIntakeHistoryTimeout();
void serviceDeviceWarningTimeout();
void serviceResetSavedDataTimeout();
bool buttonInteractionActive();
void updateMainDisplayLive();
void updateCalibrationLiveWeight(bool notify);
void refreshScaleWeight();
void resetCalibrationToDefault();
void handleTimeSync(const String &payload);
void handleSettingsWrite(const String &payload);
void handleAckWrite(const String &payload);
void streamLogsAfter(const String &afterRecordId);
